Help page
thomas7carriere/Project4806 pull request #51
Opened 2021-03-25 16:16 UTC by kellyharrison

- /survey/help [GET] controller
- drop down menu on page to allow you jump to a specific question
- Allowed the option to jump to /survey/create or /mysurveys based on what FAQ it was

2021-03-25 16:52 UTC, thomas7carriere requested changes
In helpPage.html, when creating a question it mentions to press the create question button twice per question, but I think it's just once. There's also an application log that probably shouldn't be included

2021-03-25 17:27 UTC, kellyharrison commented
@thomas7carriere Yea you're right I added too many "create questions" I'll fix that

2021-03-25 17:32 UTC, thomas7carriere commented
> @thomas7carriere Yea you're right I added too many "create questions" I'll fix that. Also where is the unused application log?

application.log.2021-03-23.0.gz, one of the files added

2021-03-26 00:29 UTC, thomas7carriere approved these changes

2021-03-26 00:33 UTC, cyang030 approved these changes

2021-03-26 00:33 UTC, Dom123k approved these changes

2021-03-26 00:33 UTC, AriSengupta approved these changes

2021-03-26 00:37 UTC, merged