Iss7_range_question
thomas7carriere/Project4806 pull request #8
Opened 2021-03-05 04:28 UTC by kellyharrison

2021-03-05 15:18 UTC, cyang030 approved these changes
If the goal is to let IntelliJ autogenerate .iml on each pom.xml update/import, perhaps add .iml into .ignore as well?
I don't have comment on whether submitting .iml each time into git or just let it autogenerate.

For the JPA part, is it worth adding an UT as well?
I did mine because I had so many issue with them, so I though it might help. Having said that I am not a web developer so need other's opinion.

2021-03-05 15:18 UTC, cyang030 commented on src/main/java/application/models/RangeQuestion.java
> +     * @return an ArrayList of integers
The collection seems to be initialized to LinkedList instead?
Maybe just say a Collections of integers?

On second thought maybe need to changes the answers explicitly to List later, because Collection may make people think a Set is also okay.

2021-03-05 16:07 UTC, thomas7carriere requested changes
Would it be possible to add testing for persisting a range Question, similar to what was done for the other 2 questions

2021-03-06 22:34 UTC, thomas7carriere approved these changes

2021-03-06 22:34 UTC, merged